### ISSUE TITLE
Decide the API framework

### ISSUE THREAD

**Issue by Abijeet** [DO-Undefined/api#1]
Need to decide the API framework

**Comment by Abijeet** [comment]
@surendrabvv - We need to make sure that the framework supports easy API development. It shouldn't be too heavy either. You can select from the list here - https://github.com/sindresorhus/awesome-nodejs#web-frameworks

We've to ensure that the framework provides enough examples and has good documentation.

**Comment by surendrabvv** [comment]
We are using express framework.
